### ISSUE TITLE
Dynamic record placeholders

### ISSUE THREAD

**Issue by srnyx** [Block2Block/HubParkour#11]
Record placeholders don't update until the server is restarted.

**Comment by Block2Block** [comment]
Unfortunately there's nothing I can do there, it's dependant on how often the plugin you're using the placeholders with looks for updates, the plugin will give up-to-date information whenever the placeholder is requested

**Comment by srnyx** [comment]
> Unfortunately there's nothing I can do there, it's dependant on how often the plugin you're using the placeholders with looks for updates, the plugin will give up-to-date information whenever the placeholder is requested

Even if I do `/dm reload`, it doesn't change. And the other placeholders update fine. So it isn't the other plugin that's causing it.
When I do `/pk reload` however, the placeholders update.

**Comment by Block2Block** [comment]
I mean I can look into it but I doubt there is much I can do about it as it grabs the value directly from the database whenever it is requested.
