### ISSUE TITLE
[SUGGESTION] Overall leaderboard

### ISSUE THREAD

**Issue by srnyx** [Block2Block/HubParkour#12]
A leaderboard that adds up all the times of the player's **completed** parkours and adds them to a leaderboard.
They would only be added once they complete **all** of the courses, and there would be a config option to make it ignore some courses.

**Comment by srnyx** [comment]
@Block2Block

**Comment by Block2Block** [comment]
Idea has been added to the queue of ideas for the 2.7 update. Link: https://trello.com/c/G0Gyd2jO/55-overall-leaderboard
