### ISSUE TITLE
[SUGGESTION] Reset confirmation

### ISSUE THREAD

**Issue by srnyx** [Block2Block/HubParkour#15]
Add a confirmation message before resetting the player's progress so that people don't accidentally misclick.

**Comment by srnyx** [comment]
@Block2Block

**Comment by Block2Block** [comment]
The only fear I have when introducing something like this is that it becomes annoying for people who are trying to speedrun, as the confirmation can just get in the way of people trying to reset. I can probably add it as a config option but I will look into it for the next version.

**Comment by Block2Block** [comment]
Released in v2.7.
