### ISSUE TITLE
Add Support for Rotating Heads, DecentHolograms

### ISSUE THREAD

**Issue by vLuckyyy** [Block2Block/HubParkour#20]
Please add support RotatingHeads and DecentHolograms + page leaderboard in decenthologram option :0

**Comment by Block2Block** [comment]
I currently have no plans to add support for more plugin API's at this time. If you wish to use those plugins and they support PlaceholderAPI, you can use the built-in placeholders provided by the plugin, which are listed on the spigot page and in #faq in Discord.
