### ISSUE TITLE
[Issue] Pressure Plate Not Triggering

### ISSUE THREAD

**Issue by MinecraftMan1013number2** [Block2Block/HubParkour#21]
If you step on the edge of a pressure plate (checkpoint, start, or end), you will see and hear the plate activate, but the checkpoint will not register. In order for the checkpoint to register, you need to step closer to the middle of the plate.

This is a problem because some parkours are not just one block wide. They might be a 2x2 or 3x3 or more.

**Comment by Block2Block** [comment]
The plugin just listens to when your player's X and Z coordinates are in the same block as the pressure plate, not when the pressure plate is actually activated, so this is not a bug and is intentional.
