### ISSUE TITLE
Reset Item "RED_BED" not working.

### ISSUE THREAD

**Issue by Oskicz** [Block2Block/HubParkour#29]
When i (or my players) want to start parkour again and use the item "reset" red_bed It teleports to the first checkpoint but not restart parkour time please fix this ;C

(Using newest version 2.7.3 on 1.19.2 server)

**Comment by Block2Block** [comment]
This is intentional. If a user was to reset and the restart point is behind the start point, it will add additional time to their parkour time, so in order to make it fair, players must run back over the pressure plate to reset their time.
