### ISSUE TITLE
I can't create 4 arenas

### ISSUE THREAD

**Issue by joao218623** [Block2Block/HubParkour#30]
When i try to save my forth arena i get this error: 
![image](https://user-images.githubusercontent.com/115410868/194761391-c7677ca8-f86b-4e78-bb9a-7f5bfcda7eca.png)

And then no commands work, the setup doens't work, the list doens't work and the delete doens't work

**Comment by Block2Block** [comment]
Are there any errors in console when you try to do that?

**Comment by Block2Block** [comment]
there has been no update to this issue so I am closing it. If the issue persists, create a new issue.
