### ISSUE TITLE
Formatting codes (e.g. bold) failing to parse when using gradients

### ISSUE THREAD

**Issue by HackuJacku** [Block2Block/HubParkour#33]
When using HubParkour 2.7.4, alongside DecentHolograms 2.8.1, for the hologram messages, special formatting codes (e.g. &l for bold) is parsing to parse.

In the config, I have specified "<#fb0000>&l{parkour-name}</#ff9315>". The output should be the parkour-name in bold, with the gradient specified. However, the outcome appears as the following image:

![image](https://user-images.githubusercontent.com/18508413/232828550-e4e8aa59-f453-4e44-9274-3d7cb6f1a8b9.png)

When reproducing this with a hologram I had created, using DecentHolograms, I am unable to reproduce this issue.

**Comment by Block2Block** [comment]
Unfortunately, there is very little I can do. I pass the values inputted directly into the DecentHolograms API, so is likely a bug with Decent Holograms.
