### ISSUE TITLE
Jenkins Private Server

### ISSUE THREAD

**Issue by allie-developments** [Block2Block/HubParkour#38]
Can't get "me.block2block.hubparkour" from Your private jenkins repo.
How to use?

**Comment by HappyAreaBean** [comment]
You can use [jitpack](https://jitpack.io/#Block2Block/HubParkour/2.7.5).
remember to select subproject too

**Comment by allie-developments** [comment]
Thanks you too!

**Comment by Block2Block** [comment]
The repository is now back in nexus, configuration is the same.
