### ISSUE TITLE
Holograms don't show up

### ISSUE THREAD

**Issue by ggtylerr** [Block2Block/HubParkour#9]
When attempting to list holograms, there's none listed. I'm assuming that's because it doesn't list the ones auto-generated from the setup.

EDIT: Also, it seems like deleting a parkour doesn't delete the holograms

![Example](https://i.vgy.me/xuvRWS.png)

**Comment by Block2Block** [comment]
That is not a bug, that is intentional. To disable the holograms disable the settings in the config. That command is meant for managing leaderboard holograms.
